"""empty message

Revision ID: 0944561d56ae
Revises: 647572fdcdc7
Create Date: 2022-08-20 00:01:33.146390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0944561d56ae'
down_revision = '647572fdcdc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'artists', ['name'])
    op.create_unique_constraint(None, 'artists', ['phone'])
    op.alter_column('venues', 'phone',
               existing_type=sa.VARCHAR(length=12),
               nullable=False)
    op.create_unique_constraint(None, 'venues', ['phone'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'venues', type_='unique')
    op.alter_column('venues', 'phone',
               existing_type=sa.VARCHAR(length=12),
               nullable=True)
    op.drop_constraint(None, 'artists', type_='unique')
    op.drop_constraint(None, 'artists', type_='unique')
    # ### end Alembic commands ###
